name: Smart Retail AI CI/CD Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    steps:

      # =========================================
      # CHECKOUT REPOSITORY
      # =========================================

      - name: Checkout Repository
        uses: actions/checkout@v4

      # =========================================
      # SETUP PYTHON
      # =========================================

      - name: Setup Python
        uses: actions/setup-python@v5

        with:
          python-version: "3.11"

      # =========================================
      # INSTALL DEPENDENCIES
      # =========================================

      - name: Install Dependencies

        run: |

          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # =========================================
      # RUN PYTEST
      # =========================================

      - name: Skip Tests
        run: echo "Skipping tests"

      # =========================================
      # BUILD DOCKER IMAGE
      # =========================================

      - name: Build Docker Image

        run: |

          docker build -t smart-retail-ai .